"Resource/UI/LoadoutPresetPanel.res"
{
	"loadout_preset_panel"
	{
		"ControlName"	"CLoadoutPresetPanel"
		"fieldName"		"loadout_preset_panel"
		"ypos"			"-150"
		"presetbutton_kv"
		{
			"ypos"			"-150"
			"zpos"			"20"
			"wide"			"15"
			"tall"			"15"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			"tabPosition"	"0"
			"font"			"Lollipop_Small12"
			"textAlignment"	"center"
			"textinsetx"	"0"
			"dulltext"		"0"
			"brighttext"	"0"
			"Command"		""
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"centerwrap"	"1"
			"FgColor_override" "BoxLighter"
			"defaultFgColor_override" "BoxLighter"
			"armedFgColor_override" "BoxLighter"
			"depressedFgColor_override" "BoxLighter"
			"selectedFgColor_override" "BoxLighter"
			"defaultBgColor_override" "TanDarker"
			"armedBgColor_override" "TanDarker"
			"depressedBgColor_override" "TanDarker"
			"selectedBgColor_override" "TanDarker"
		}			
	}
}
